## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
ar = np.random.randint(1, 10, 10)
print(ar)

for i in range(0, len(ar)):
    if 3 < ar[i] < 8:
        ar[i] *= -1
print(ar)

[5 1 8 1 4 4 3 9 6 9]
[-5  1  8  1 -4 -4  3  9 -6  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
ar = np.random.randint(1, 10, 10)
print(ar)

max_val = np.max(ar)
ar = np.array([i if i != max_val else 0 for i in ar])
print(ar)

[7 2 9 1 1 1 2 1 7 1]
[7 2 0 1 1 1 2 1 7 1]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
import itertools as it
import numpy as np

array = np.random.randint(0, 10, [2, 2]) # np.array([[1, 2], [3, 4]])
print(array, '\n')

combinations = it.product(array.flatten(), array.flatten())

for combination in combinations:
    print(combination)

[[7 1]
 [7 2]] 

(7, 7)
(7, 1)
(7, 7)
(7, 2)
(1, 7)
(1, 1)
(1, 7)
(1, 2)
(7, 7)
(7, 1)
(7, 7)
(7, 2)
(2, 7)
(2, 1)
(2, 7)
(2, 2)


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = np.random.randint(0, 8, (8, 3))
B = np.random.randint(0, 4, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1, 2, 3)) >= B.shape[1]).nonzero()[0]
print(A)
print()
print(B)
print()
print(rows)

[[4 6 0]
 [0 6 7]
 [0 1 7]
 [1 1 6]
 [2 0 0]
 [0 4 7]
 [7 7 0]
 [3 5 6]]

[[0 3]
 [2 2]]

[4]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
Z = np.random.randint(0, 2, (10, 3))
E = np.logical_and.reduce(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
print(Z, '\n', 'row count:', len(Z[:]), '\n')
print(U, '\n', 'row count:', len(U[:]))

[[1 1 1]
 [1 0 1]
 [0 0 1]
 [1 1 1]
 [1 0 1]
 [1 1 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]] 
 row count: 10 

[[1 0 1]
 [0 0 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]] 
 row count: 7


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [22]:
ar = np.random.randint(0, 2, (10, 3))
ar_ = np.unique(ar, axis=0)
print(ar, '\n')
print(ar_)

[[1 1 0]
 [0 0 0]
 [1 0 0]
 [0 1 0]
 [1 1 0]
 [1 1 0]
 [0 1 0]
 [1 1 0]
 [1 0 1]
 [0 1 0]] 

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
def numpy_1(X):    
    X1 = np.diag(X)
    X2 = X1[X1 != 0]
    return X2.prod() # np.prod(np.diag(X)[np.diag(X) != 0])


def python_1(X):
    diag_nn = []
    r, c = X.shape
    cur_row = 0
    for cur_col in range(c):
        if cur_row < r and X[cur_row, cur_col] != 0:
            diag_nn.append(X[cur_row, cur_col])
        cur_row += 1

    mult = None
    for i in diag_nn:
        if not mult:
            mult = 1
        mult *= i
        
    return mult
    

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(numpy_1(X))
print(python_1(X))

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [10]:
def numpy_2(x, y):
    x_nums, x_counts = np.unique(x, return_counts=True)
    y_nums, y_counts = np.unique(y, return_counts=True)
    
    if(np.shape(x_nums) != np.shape(y_nums)):
        return False
    
    if(np.any(x_nums != y_nums) or np.any(x_counts != y_counts)):
        return False
    
    return True


def python_2(x, y):
    if len(x) != len(y):
        return False

    x.sort()
    y.sort()
    for i in range(len(x)):
        if x[i] != y[i]:
            return False
    
    return True


x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
print(numpy_2(x, y))
print(python_2(x, y))

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [11]:
def numpy_3(x):
    a = np.where(x == 0)
    b = np.array(a).flatten() + 1
    c = b[b < len(x)]
    return x[c].max()


def python_3(x):
    prev = None
    maxi = None
    for i in x:
        if prev == None:
            prev = i
            continue

        if prev == 0:
            maxi = i if (maxi == None or i > maxi) else maxi
        
        prev = i
    return maxi


x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(numpy_3(x))
print(python_3(x))

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [12]:
def numpy_4(x):
    return np.unique(x, return_counts=True)


from collections import defaultdict
def python_4(x):
    d = defaultdict(int)
    for i in x:
        d[i] += 1
    return list(d.keys()), list(d.values())


x = np.array([2, 2, 2, 3, 3, 3, 5])
print(numpy_4(x))
print(python_4(x))

(array([2, 3, 5]), array([3, 3, 1]))
([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [29]:
import math
import scipy
import time


def numpy_5(a, b):
    P = np.add.outer(np.sum(a ** 2, axis=1), np.sum(b ** 2, axis=1))
    N = np.dot(a, b.T)
    return np.sqrt(P - 2 * N)


def python_5(a, b):
    res = []
    for i in range(len(a)):
        curr_list = []
        for j in range(len(b)):
            distance = 0
            for k in range(len(b[0])):
                distance += (a[i][k] - b[j][k]) ** 2
            curr_list.append(round(math.sqrt(distance), 7))
        res.append(curr_list)
    return np.array(res)


a = np.random.randint(1, 10, (5, 3))
b = np.random.randint(1, 10, (4, 3))


start_time = time.time()
print(numpy_5(a, b), '\t time(s): ', (time.time() - start_time))

start_time = time.time()
print(python_5(a, b), '\t time(s): ', (time.time() - start_time))

start_time = time.time()
print(scipy.spatial.distance.cdist(a, b, metric='euclidean'), '\t time(s): ', (time.time() - start_time))

[[ 3.74165739  1.          7.07106781  7.68114575]
 [ 9.2736185  10.81665383  5.09901951  7.        ]
 [ 5.91607978  8.24621125  4.35889894  8.83176087]
 [ 6.70820393  7.61577311  8.77496439  5.09901951]
 [ 4.          6.55743852  6.63324958  5.74456265]] 	 time(s):  6.937980651855469e-05
[[ 3.7416574  1.         7.0710678  7.6811457]
 [ 9.2736185 10.8166538  5.0990195  7.       ]
 [ 5.9160798  8.2462113  4.3588989  8.8317609]
 [ 6.7082039  7.6157731  8.7749644  5.0990195]
 [ 4.         6.5574385  6.6332496  5.7445626]] 	 time(s):  9.083747863769531e-05
[[ 3.74165739  1.          7.07106781  7.68114575]
 [ 9.2736185  10.81665383  5.09901951  7.        ]
 [ 5.91607978  8.24621125  4.35889894  8.83176087]
 [ 6.70820393  7.61577311  8.77496439  5.09901951]
 [ 4.          6.55743852  6.63324958  5.74456265]] 	 time(s):  5.459785461425781e-05


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [14]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [15]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [16]:
calories_CrunchieMunchies = 60
average_calories = np.mean(calorie_stats) - calories_CrunchieMunchies
print(average_calories)

46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [17]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [18]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [19]:
n20th_percentile = np.percentile(calorie_stats, 20)
print('20th_percentile:', n20th_percentile)
n15th_percentile = np.percentile(calorie_stats, 15)
print('15th_percentile:', n15th_percentile)
n10th_percentile = np.percentile(calorie_stats, 10)
print('10th_percentile:', n10th_percentile)
n05th_percentile = np.percentile(calorie_stats, 5)
print('05th_percentile:', n05th_percentile)
n03th_percentile = np.percentile(calorie_stats, 3)
print('03th_percentile:', n03th_percentile)
n04th_percentile = np.percentile(calorie_stats, 4)
print('04th_percentile:', n04th_percentile)

nth_percentile = n04th_percentile

20th_percentile: 100.0
15th_percentile: 90.0
10th_percentile: 90.0
05th_percentile: 70.0
03th_percentile: 55.599999999999994
04th_percentile: 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [20]:
more_calories = calorie_stats[calorie_stats > 60].size * 100 / calorie_stats.size
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [21]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.